# Compiler and Flags
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98 -I. # Include current directory for headers

# Source Files
SRCS = main.cpp Fixed.cpp

# Object Files - corresponding .o file for each .cpp file
OBJS = $(SRCS:.cpp=.o)

# Executable Name
NAME = fixed_test

# Default Target: Build the executable
all: $(NAME)

# Rule to link the object files into the final executable
$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)
	@echo "$(NAME) executable created."

# Rule to compile .cpp files into .o object files
# $<: the name of the first prerequisite (the .cpp file)
# $@: the name of the target (the .o file)
%.o: %.cpp Fixed.hpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Target to remove object files and the executable
clean:
	rm -f $(OBJS)
	@echo "Object files removed."

# Target to remove everything generated by the Makefile
fclean: clean
	rm -f $(NAME)
	@echo "Executable removed."

# Target to recompile everything from scratch
re: fclean all

# Phony targets are rules that don't represent actual files
.PHONY: all clean fclean re